# version: "3.1"

# services:
#   mongo:
#     image: mongo
#     restart: always
#     container_name: mongodb
#     ports:
#       - 27017:27017
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: hrithik
#       MONGO_INITDB_ROOT_PASSWORD: hrithik
#     volumes:
#       - ./db_data/:/data/db/

version: "3.1"

services:
  mongo:
    image: "mongo"
    restart: "always"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hrithik
      MONGO_INITDB_ROOT_PASSWORD: hrithik
    volumes:
      - ./db_data/:/data/db
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=4000
      - JWT_SECRET={secret anything that you like}
      - MONGO_URI=mongodb://{usename}:{password}@mongo:27017/
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
  logs:
